apiVersion: v1
kind: Pod
metadata:
  name: demo-pv-writer-pod
spec:
  volumes:
    - name: demo-pv-storage
      persistentVolumeClaim:
        claimName: demo-pv-claim
  containers:
    - name: demo-pv-writer-container
      image: bapadua/demo-pv-writer:latest
      ports:
        - containerPort: 8083
          name: "demo-pv-writer"
      volumeMounts:
        - mountPath: "/mnt/tmp"
          name: demo-pv-storage



